version: 2
updates:
# GitHub Actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/bson
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/cache/prime
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/cache/restore
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/docker/cache/prime
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/docker/cache/restore
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/docker/fetch
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/docker/shas
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/envoy/android/pre
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/envoy/ci/env
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/envoy/ci/request
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/envoy/ios/post
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/envoy/run/summary
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/foreach
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/github/artifact/download
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/github/checkout
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/github/command
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/github/env/load
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/github/env/save
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/github/env/summary
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/github/merge-commit
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/github/pr
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/github/run
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/json/table
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/upload/diff
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/using/recurse
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: /gh-actions/using/steps
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"

# Python (pip)
- package-ecosystem: pip
  directory: /gh-actions/gcp/setup
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: pip
  directory: /bazel
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: pip
  directory: /bazel/website
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: pip
  directory: /deps
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: pip
  directory: /deps/flake8
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: pip
  directory: /deps/mypy
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: pip
  directory: /deps/pytest
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"

# Bazel
- package-ecosystem: bazel
  directory: /bazel
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"

# Rust (Cargo)
- package-ecosystem: cargo
  directory: /rust
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"

# npm
- package-ecosystem: npm
  directory: /gh-actions/appauth
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: npm
  directory: /gh-actions/dispatch
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: npm
  directory: /gh-actions/github/checks
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: npm
  directory: /gh-actions/github/mutex
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: npm
  directory: /gh-actions/github/script/run
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: npm
  directory: /gh-actions/hashfiles
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: npm
  directory: /gh-actions/jq
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: npm
  directory: /gh-actions/retest
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
- package-ecosystem: npm
  directory: /gh-actions/torun
  schedule:
    interval: daily
  groups:
    dependencies:
      patterns:
      - "*"
